version: '3.8'

services:

  jupyterlab:

    image: diy-ds-cloud/project-template-dev:latest

    build:
      context: ./
      dockerfile: binder/Dockerfile
      args:
        - ARG NB_USER=jovyan
        - ARG NB_UID=1000

    ports:
      - 8888:8888

    environment:
      - JUPYTER_TOKEN=asdf

    command: ["jupyter", "lab", "--NotebookApp.default_url=/lab/", "--ip=0.0.0.0", "--port=8888"]