apiVersion: v1
kind: Service
metadata:
  name: {{ include "diy.fullname" . }}-scheduler
  labels:
    app: {{ template "diy.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "diy.chart" . }}
    component: scheduler
spec:
  type: {{ .Values.scheduler.ui.serviceType }}
  ports:
    - name: {{ include "diy.fullname" .}}-ui
      port: {{ .Values.scheduler.ui.servicePort }}
      targetPort: {{ .Values.scheduler.ui.targetPort }}
    - name: {{ include "diy.fullname" .}}-controller
      port: {{ .Values.scheduler.controller.servicePort }}
      targetPort: {{ .Values.scheduler.controller.targetPort }}
  selector:
    app: {{ template "diy.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler